language: go

go:
  - "1.14"

services:
  - docker

jobs:
  include:

    - stage: test
      script: make test

    - stage: build and push
      if: tag IS present AND branch = master AND tag =~ ^\d+\.\d+(\.\d+)?$ AND fork = false
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - make docker-push

