language: go

go:
  - "1.15"

services:
  - docker
  - postgresql

jobs:
  include:

    - stage: test
      script: make ci-test

    - stage: build and push
      if: tag IS present AND tag =~ ^\d+\.\d+(\.\d+)?$
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - make docker-push

